version: '3.8'

services:
  app1:
    build: ./app
    container_name: backend_app1
    volumes:
      - ./app:/usr/src/app
    command: ["node", "server1.js"]
    ports:
      - "3001:3001"

  app2:
    build: ./app
    container_name: backend_app2
    volumes:
      - ./app:/usr/src/app
    command: ["node", "server2.js"]
    ports:
      - "3002:3002"

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
