version: '3.8'
services:
  service-v1:
    build: ./services/service-v1
    container_name: service_v1

  service-v2:
    build: ./services/service-v2
    container_name: service_v2

  nginx:
    image: openresty/openresty:alpine
    container_name: nginx_api_gateway
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - service-v1
      - service-v2
