version: '3.8'

services:
  app:
    build: ./app
    container_name: backend_app_secure
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_secure
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
