version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
