version: '3.8'

services:
  app:
    build: ./app
    container_name: backend_app_ssl
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_https
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
